Update protobuf definition.
ns1/pulsar-rum pull request #1
Opened 2020-09-30 20:19 UTC by antoniovl

Just a small update to the docs on the TTL regarding static beacons.

2020-09-30 20:25 UTC, jroyalty requested changes

2020-09-30 20:25 UTC, jroyalty commented on go.mod
> +go 1.15
What's the minimum Go version that can be supported here? I'm not sure we have to pin to latest.

2020-09-30 20:27 UTC, antoniovl commented on go.mod
> +go 1.15
I think go 1.13. Go 1.11 and 1.12 was on pre-release.

2020-10-01 01:12 UTC, jroyalty approved these changes

2020-10-01 01:13 UTC, merged