Added authentication support.
ns1/pulsar-rum pull request #3
Opened 2020-11-04 06:50 UTC by antoniovl

Added a sample authentication support to the gRPC client.

2020-11-10 19:04 UTC, mvkushnir approved these changes

2020-11-10 19:41 UTC, mvkushnir approved these changes

2020-11-11 20:05 UTC, jroyalty requested changes

2020-11-11 20:05 UTC, jroyalty commented on cmd/example_client/grpc_example_client.go
> +		"x-ns1-key": a.key,
Let's make this `X-NSONE-Key` by default. And remove the docs above, stating the alternatives.  Those aren't "official".

2020-11-11 21:52 UTC, jroyalty approved these changes

2020-11-11 22:04 UTC, merged