Implemented BulkBeacon Protobuf Definitions versions 2 and 3
ns1/pulsar-rum pull request #5
Opened 2021-04-05 16:51 UTC by antoniovl

This PR implements a new definition for the BulkBeacon gRPC endpoint that enables the ability to separate latency from availability for performance.

2021-04-19 20:50 UTC, jroyalty requested changes

2021-04-19 20:50 UTC, jroyalty commented on Makefile
> +# Copyright 2020 NSONE, Inc.
Nit: Update copyright to 2021

2021-04-19 20:50 UTC, jroyalty commented on Makefile
> +hash:
Still required?

2021-04-19 20:50 UTC, jroyalty commented on pkg/bulkbeacon/auth.go
> +// Copyright 2020 NSONE, Inc.
Nit: Update copyright to 2021

2021-04-19 20:50 UTC, jroyalty commented on pkg/bulkbeacon/auth.go
> +import "context"
`context` is provided by the core protobuf libs?

2021-04-19 20:50 UTC, jroyalty commented on cmd/example_client_v2/main.go
> +					Metric: &pb.Payload_PerfScore{
How about a better example here?  Two payloads?  One with Latency and static avail score and another with the opposite?

2021-04-19 20:50 UTC, jroyalty commented on README.md
> +found on `proto/bulkbeacon/{version}/bulkbeacon.proto`, with `version` taking values
Typo: `found on` -> `found in`

2021-04-19 20:50 UTC, jroyalty commented on README.md
> +We currently support 2 protocol buffers + gRPC versions for Bulk Beacons. Each one can be
Maybe: ..."two formats for gRPC and HTTP+JSON"?

2021-04-20 01:27 UTC, antoniovl commented on cmd/example_client_v2/main.go
> +// Copyright 2020 NSONE, Inc.
Both examples were updated.

2021-04-20 02:34 UTC, antoniovl commented on README.md
> +found on `proto/bulkbeacon/{version}/bulkbeacon_{version}.proto`, with version taking values
Thanks.

2021-04-20 02:36 UTC, antoniovl commented on Makefile
> +hash:
Not needed, deleted.

2021-04-20 02:39 UTC, antoniovl commented on pkg/bulkbeacon/auth.go
> +import "context"
By the gRPC service. The struct implements `grpc.PerRPCCredentials` interface, and one method signature has a parameter of type context.

2021-04-20 02:39 UTC, antoniovl commented on README.md
> +found on `proto/bulkbeacon/{version}/bulkbeacon.proto`, with `version` taking values
fixed

2021-04-20 02:42 UTC, antoniovl commented on README.md
> +We currently support 2 protocol buffers + gRPC versions for Bulk Beacons. Each one can be
Makes sense. Changed.

2021-04-21 01:34 UTC, antoniovl commented on cmd/example_client_v2/main.go
> +					Metric: &pb.Payload_PerfScore{
Added more samples.

2021-04-21 02:29 UTC, jroyalty approved these changes

2021-04-21 02:30 UTC, merged